server:
  port: 8080
spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: vehicle
          uri: lb://vehicle-service
          predicates:
            - Path=/vehicles/**
